version: '3.8'

services:
  # Docker Registry
  registry:
    image: registry:2
    container_name: whanos-registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    restart: unless-stopped
    networks:
      - whanos-network

  # Jenkins CI/CD
  jenkins:
    image: jenkins/jenkins:lts
    container_name: whanos-jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./images:/var/jenkins_home/whanos-images
      - ./jenkins:/var/jenkins_home/whanos-jenkins
      - ./kubernetes:/var/jenkins_home/whanos-k8s-templates
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_REGISTRY=registry:5000
    restart: unless-stopped
    networks:
      - whanos-network
    depends_on:
      - registry

volumes:
  registry-data:
    driver: local
  jenkins-data:
    driver: local

networks:
  whanos-network:
    driver: bridge
