# Whanos Befunge Base Image
FROM alpine:latest

# Set shell to bash
RUN apk add --no-cache bash gcc musl-dev make git
SHELL ["/bin/bash", "-c"]

# Set working directory
WORKDIR /app

# Install a Befunge interpreter
RUN git clone https://github.com/catseye/Befunge-93.git /tmp/befunge && \
    cd /tmp/befunge && \
    gcc -o /usr/local/bin/befunge src/befunge.c && \
    rm -rf /tmp/befunge
