# Whanos C Standalone Image
FROM gcc:latest

# Set shell to bash
SHELL ["/bin/bash", "-c"]

# Set working directory
WORKDIR /app

# Install make
RUN apt-get update && apt-get install -y make && rm -rf /var/lib/apt/lists/*

# Copy application source code
COPY . /app/

# Build the application using make
RUN make

# Clean up unnecessary files
RUN rm -rf *.c *.h Makefile *.o

# Define the execution command
CMD ["./compiled-app"]
